### ISSUE TITLE
Cannot dynamically link compiled modules

### ISSUE THREAD

**Issue by nmec** [mhart/alpine-node#35]
## Summary

Native modules that use dynamic linking cannot be used. This may be related to the `--fully-static` arg used during compiling.
## Steps to reproduce
1. `npm install bcrypt`
2. `require('bcrypt');`
## Expected results

Module is required and available to use.
## Actual results

Error is thrown:

```
/app/node_modules/bindings/bindings.js:83
    throw e
    ^
Error: Dynamic loading not supported
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at bindings (/app/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/app/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/app/models/user.js:6:37)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

**Comment by mhart** [comment]
If you're using one of the `base` builds, then yeah, you can't use native modules. You'll have to use one of the normal builds

**Comment by mhart** [comment]
Is that the case? That you're using a `base` or `base-*` image? If so, I'll close this out – by definition you can't dynamically load from a static binary

**Comment by mhart** [comment]
Going to close this unless you want to add anything – I think the README makes it fairly clear that the `base-*` images are statically compiled binaries, and the example states that you should only use it if you have no native dependencies.

If you weren't using a `base-*` image, please reopen – it should be possible to use native modules with the other tags (`latest`, `4`, etc)

**Comment by nmec** [comment]
Thanks for clarifying - as a quick workaround I switched to bcryptjs, if I get a bit more time I'll see if I can get it working with the other image.
