### ISSUE TITLE
Can not install node module kerberos

### ISSUE THREAD

**Issue by fantasy8-me** [mhart/alpine-node#52]
Installing kerberos module and get below error, which can be solved by installing libkrb5-dev (Debian/Ubuntu) or krb5-devel (CentOS) , accrording https://github.com/christkv/kerberos/issues/21.

Is there a package available in **alpine** ?

```
> kerberos@0.0.21 install /home/src/reedsec-risk-gateway/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/home/src/reedsec-risk-gateway/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
compilation terminated.
kerberos.target.mk:100: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/home/src/reedsec-risk-gateway/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.12-boot2docker
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/src/reedsec-risk-gateway/node_modules/kerberos
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
```

**Comment by mhart** [comment]
No idea, you can search Alpine packages here: https://pkgs.alpinelinux.org/packages

**Comment by mhart** [comment]
Looks like `krb5-dev` will do the trick? https://pkgs.alpinelinux.org/package/v3.4/main/x86_64/krb5-dev

**Comment by mhart** [comment]
(closing this as it's not an `alpine-node` issue)

**Comment by fantasy8-me** [comment]
Yeah, `krb5-dev` did work, thanks @mhart.

To make thing Below is the building log of kerberos module after `krb5-dev` is installed

```
> kerberos@0.0.21 install /home/src/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

make: Entering directory '/home/src/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
../lib/kerberosgss.c:36:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic push
 ^
../lib/kerberosgss.c:37:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic ignored "-Wdeprecated-declarations"
 ^
../lib/kerberosgss.c: In function 'authenticate_gss_client_wrap':
../lib/kerberosgss.c:446:19: warning: variable 'server_conf_flags' set but not used [-Wunused-but-set-variable]
   char buf[4096], server_conf_flags;
                   ^
../lib/kerberosgss.c: At top level:
../lib/kerberosgss.c:1236:0: warning: ignoring #pragma clang diagnostic [-Wunknown-pragmas]
 #pragma clang diagnostic pop
 ^
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/obj.target/kerberos.node
  COPY Release/kerberos.node
make: Leaving directory '/home/src/node_modules/kerberos/build'
-
```

**Comment by mfkenson** [comment]
@fantasy8-me I have the same log. How to fix this? This does not look like a successful build.
