### ISSUE TITLE
[base build] Dynamic loading not supported

### ISSUE THREAD

**Issue by kouhin** [mhart/alpine-node#83]
```
docker run -it --rm mhart/alpine-node:base /bin/sh -c "echo \$PATH && apk add --no-cache curl python g++ make tar gnupg && \
curl -o- -L https://yarnpkg.com/install.sh | sh && \
ln -sf /root/.yarn/bin/yarn /usr/local/bin && \
yarn add bcrypt && node -p require\(\'bcrypt\'\).genSaltSync\(10\)"
```

Output: 

```
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Dynamic loading not supported
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

The common build is OK. I think it may be caused by `--fully-static` flag.

**Comment by kouhin** [comment]
@mhart  I'm sorry that I found this issue just now. 
https://github.com/mhart/alpine-node/issues/35

However base build + yarn is really desirable.
